name: Build check

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: Shane32/SharedWorkflows/.github/workflows/build-check.yml@v2
    with:
      dotnet_folder: '.'
      data_collector: ''
      coverage_report: false
